checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN-}"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.1.1.cjs
