name: Tag

on:
  push:
    tags:
      - "@mia-platform/**"

jobs:
  release:
    name: Release package on npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: echo "tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: .nvmrc
          check-latest: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: yarn install --immutable

      - name: Prepare NPM
        id: prepare-npm-package
        run: |
          TAGS=${{ steps.extract_tag.outputs.tag }}
          echo "package=$(echo $TAGS | sed -r 's/@mia-platform\/(.*)@.*$/@mia-platform\/\1/')" >> $GITHUB_OUTPUT

      - name: Build
        run: yarn workspace ${{ steps.prepare-npm-package.outputs.package }} build

      - name: Publish
        run: yarn workspace ${{ steps.prepare-npm-package.outputs.package }} npm publish
